from enum import Enum
from typing import Dict


class DriverId(Enum):
    CARLOS_SAINZ = 0
    DANIIL_KVYAT = 1
    DANIEL_RICCIARDO = 2
    FERNANDO_ALONSO = 3
    FELIPE_MASSA = 4
    KIMI_RÄIKKÖNEN = 6
    LEWIS_HAMILTON = 7
    MAX_VERSTAPPEN = 9
    NICO_HULKENBURG = 10
    KEVIN_MAGNUSSEN = 11
    ROMAIN_GROSJEAN = 12
    SEBASTIAN_VETTEL = 13
    SERGIO_PEREZ = 14
    VALTTERI_BOTTAS = 15
    ESTEBAN_OCON = 17
    LANCE_STROLL = 19
    ARRON_BARNES = 20
    MARTIN_GILES = 21
    ALEX_MURRAY = 22
    LUCAS_ROTH = 23
    IGOR_CORREIA = 24
    SOPHIE_LEVASSEUR = 25
    JONAS_SCHIFFER = 26
    ALAIN_FOREST = 27
    JAY_LETOURNEAU = 28
    ESTO_SAARI = 29
    YASAR_ATIYEH = 30
    CALLISTO_CALABRESI = 31
    NAOTA_IZUM = 32
    HOWARD_CLARKE = 33
    WILHEIM_KAUFMANN = 34
    MARIE_LAURSEN = 35
    FLAVIO_NIEVES = 36
    PETER_BELOUSOV = 37
    KLIMEK_MICHALSKI = 38
    SANTIAGO_MORENO = 39
    BENJAMIN_COPPENS = 40
    NOAH_VISSER = 41
    GERT_WALDMULLER = 42
    JULIAN_QUESADA = 43
    DANIEL_JONES = 44
    ARTEM_MARKELOV = 45
    TADASUKE_MAKINO = 46
    SEAN_GELAEL = 47
    NYCK_DE_VRIES = 48
    JACK_AITKEN = 49
    GEORGE_RUSSELL = 50
    MAXIMILIAN_GÜNTHER = 51
    NIREI_FUKUZUMI = 52
    LUCA_GHIOTTO = 53
    LANDO_NORRIS = 54
    SÉRGIO_SETTE_CÂMARA = 55
    LOUIS_DELÉTRAZ = 56
    ANTONIO_FUOCO = 57
    CHARLES_LECLERC = 58
    PIERRE_GASLY = 59
    ALEXANDER_ALBON = 62
    NICHOLAS_LATIFI = 63
    DORIAN_BOCCOLACCI = 64
    NIKO_KARI = 65
    ROBERTO_MERHI = 66
    ARJUN_MAINI = 67
    ALESSIO_LORANDI = 68
    RUBEN_MEIJER = 69
    RASHID_NAIR = 70
    JACK_TREMBLAY = 71
    DEVON_BUTLER = 72
    LUKAS_WEBER = 73
    ANTONIO_GIOVINAZZI = 74
    ROBERT_KUBICA = 75
    ALAIN_PROST = 76
    AYRTON_SENNA = 77
    NOBUHARU_MATSUSHITA = 78
    NIKITA_MAZEPIN = 79
    GUANYA_ZHOU = 80
    MICK_SCHUMACHER = 81
    CALLUM_ILOTT = 82
    JUAN_MANUEL_CORREA = 83
    JORDAN_KING = 84
    MAHAVEER_RAGHUNATHAN = 85
    TATIANA_CALDERON = 86
    ANTHOINE_HUBERT = 87
    GUILIANO_ALESI = 88
    RALPH_BOSCHUNG = 89
    MICHAEL_SCHUMACHER = 90
    DAN_TICKTUM = 91
    MARCUS_ARMSTRONG = 92
    CHRISTIAN_LUNDGAARD = 93
    YUKI_TSUNODA = 94
    JEHAN_DARUVALA = 95
    GULHERME_SAMAIA = 96
    PEDRO_PIQUET = 97
    FELIPE_DRUGOVICH = 98
    ROBERT_SCHWARTZMAN = 99
    ROY_NISSANY = 100
    MARINO_SATO = 101
    AIDAN_JACKSON = 102
    CASPER_AKKERMAN = 103
    JENSON_BUTTON = 109
    DAVID_COULTHARD = 110
    NICO_ROSBERG = 111
    OSCAR_PIASTRI = 112
    LIAM_LAWSON = 113
    JURI_VIPS = 114
    THEO_POURCHAIRE = 115
    RICHARD_VERSCHOOR = 116
    LIRIM_ZENDELI = 117
    DAVID_BECKMANN = 118
    ALESSIO_DELEDDA = 121
    BENT_VISCAAL = 122
    ENZO_FITTIPALDI = 123
    MARK_WEBBER = 125
    JACQUES_VILLENEUVE = 126
    JAKE_HUGHES = 127
    FREDERICK_VESTI = 128
    OLLI_CALDWELL = 129
    LOGAN_SARGEANT = 130
    CEM_BOLUKBASI = 131
    AYUMA_IWASA = 132
    CLEMENT_NOVALAK = 133
    DENNIS_HAUGER = 134
    CALAN_WILLIAMS = 135
    JACK_DOOHAN = 136
    AMAURY_CORDEEL = 137
    MIKA_HAKKINEN = 138
    IGNASI_FIBLA = 255


DRIVER_NAMES: Dict[int, str] = {
    DriverId.CARLOS_SAINZ.value: "Carlos Sainz",
    DriverId.DANIIL_KVYAT.value: "Daniil Kvyat",
    DriverId.DANIEL_RICCIARDO.value: "Daniel Ricciardo",
    DriverId.FERNANDO_ALONSO.value: "Fernando Alonso",
    DriverId.FELIPE_MASSA.value: "Felipe Massa",
    DriverId.KIMI_RÄIKKÖNEN.value: "Kimi Räikkönen",
    DriverId.LEWIS_HAMILTON.value: "Lewis Hamilton",
    DriverId.MAX_VERSTAPPEN.value: "Max Verstappen",
    DriverId.NICO_HULKENBURG.value: "Nico Hulkenburg",
    DriverId.KEVIN_MAGNUSSEN.value: "Kevin Magnussen",
    DriverId.ROMAIN_GROSJEAN.value: "Romain Grosjean",
    DriverId.SEBASTIAN_VETTEL.value: "Sebastian Vettel",
    DriverId.SERGIO_PEREZ.value: "Sergio Perez",
    DriverId.VALTTERI_BOTTAS.value: "Valtteri Bottas",
    DriverId.ESTEBAN_OCON.value: "Esteban Ocon",
    DriverId.LANCE_STROLL.value: "Lance Stroll",
    DriverId.ARRON_BARNES.value: "Arron Barnes",
    DriverId.MARTIN_GILES.value: "Martin Giles",
    DriverId.ALEX_MURRAY.value: "Alex Murray",
    DriverId.LUCAS_ROTH.value: "Lucas Roth",
    DriverId.IGOR_CORREIA.value: "Igor Correia",
    DriverId.SOPHIE_LEVASSEUR.value: "Sophie Levasseur",
    DriverId.JONAS_SCHIFFER.value: "Jonas Schiffer",
    DriverId.ALAIN_FOREST.value: "Alain Forest",
    DriverId.JAY_LETOURNEAU.value: "Jay Letourneau",
    DriverId.ESTO_SAARI.value: "Esto Saari",
    DriverId.YASAR_ATIYEH.value: "Yasar Atiyeh",
    DriverId.CALLISTO_CALABRESI.value: "Callisto Calabresi",
    DriverId.NAOTA_IZUM.value: "Naota Izum",
    DriverId.HOWARD_CLARKE.value: "Howard Clarke",
    DriverId.WILHEIM_KAUFMANN.value: "Wilheim Kaufmann",
    DriverId.MARIE_LAURSEN.value: "Marie Laursen",
    DriverId.FLAVIO_NIEVES.value: "Flavio Nieves",
    DriverId.PETER_BELOUSOV.value: "Peter Belousov",
    DriverId.KLIMEK_MICHALSKI.value: "Klimek Michalski",
    DriverId.SANTIAGO_MORENO.value: "Santiago Moreno",
    DriverId.BENJAMIN_COPPENS.value: "Benjamin Coppens",
    DriverId.NOAH_VISSER.value: "Noah Visser",
    DriverId.GERT_WALDMULLER.value: "Gert Waldmuller",
    DriverId.JULIAN_QUESADA.value: "Julian Quesada",
    DriverId.DANIEL_JONES.value: "Daniel Jones",
    DriverId.ARTEM_MARKELOV.value: "Artem Markelov",
    DriverId.TADASUKE_MAKINO.value: "Tadasuke Makino",
    DriverId.SEAN_GELAEL.value: "Sean Gelael",
    DriverId.NYCK_DE_VRIES.value: "Nyck De Vries",
    DriverId.JACK_AITKEN.value: "Jack Aitken",
    DriverId.GEORGE_RUSSELL.value: "George Russell",
    DriverId.MAXIMILIAN_GÜNTHER.value: "Maximilian Günther",
    DriverId.NIREI_FUKUZUMI.value: "Nirei Fukuzumi",
    DriverId.LUCA_GHIOTTO.value: "Luca Ghiotto",
    DriverId.LANDO_NORRIS.value: "Lando Norris",
    DriverId.SÉRGIO_SETTE_CÂMARA.value: "Sérgio Sette Câmara",
    DriverId.LOUIS_DELÉTRAZ.value: "Louis Delétraz",
    DriverId.ANTONIO_FUOCO.value: "Antonio Fuoco",
    DriverId.CHARLES_LECLERC.value: "Charles Leclerc",
    DriverId.PIERRE_GASLY.value: "Pierre Gasly",
    DriverId.ALEXANDER_ALBON.value: "Alexander Albon",
    DriverId.NICHOLAS_LATIFI.value: "Nicholas Latifi",
    DriverId.DORIAN_BOCCOLACCI.value: "Dorian Boccolacci",
    DriverId.NIKO_KARI.value: "Niko Kari",
    DriverId.ROBERTO_MERHI.value: "Roberto Merhi",
    DriverId.ARJUN_MAINI.value: "Arjun Maini",
    DriverId.ALESSIO_LORANDI.value: "Alessio Lorandi",
    DriverId.RUBEN_MEIJER.value: "Ruben Meijer",
    DriverId.RASHID_NAIR.value: "Rashid Nair",
    DriverId.JACK_TREMBLAY.value: "Jack Tremblay",
    DriverId.DEVON_BUTLER.value: "Devon Butler",
    DriverId.LUKAS_WEBER.value: "Lukas Weber",
    DriverId.ANTONIO_GIOVINAZZI.value: "Antonio Giovinazzi",
    DriverId.ROBERT_KUBICA.value: "Robert Kubica",
    DriverId.ALAIN_PROST.value: "Alain Prost",
    DriverId.AYRTON_SENNA.value: "Ayrton Senna",
    DriverId.NOBUHARU_MATSUSHITA.value: "Nobuharu Matsushita",
    DriverId.NIKITA_MAZEPIN.value: "Nikita Mazepin",
    DriverId.GUANYA_ZHOU.value: "Guanya Zhou",
    DriverId.MICK_SCHUMACHER.value: "Mick Schumacher",
    DriverId.CALLUM_ILOTT.value: "Callum Ilott",
    DriverId.JUAN_MANUEL_CORREA.value: "Juan Manuel Correa",
    DriverId.JORDAN_KING.value: "Jordan King",
    DriverId.MAHAVEER_RAGHUNATHAN.value: "Mahaveer Raghunathan",
    DriverId.TATIANA_CALDERON.value: "Tatiana Calderon",
    DriverId.ANTHOINE_HUBERT.value: "Anthoine Hubert",
    DriverId.GUILIANO_ALESI.value: "Guiliano Alesi",
    DriverId.RALPH_BOSCHUNG.value: "Ralph Boschung",
    DriverId.MICHAEL_SCHUMACHER.value: "Michael Schumacher",
    DriverId.DAN_TICKTUM.value: "Dan Ticktum",
    DriverId.MARCUS_ARMSTRONG.value: "Marcus Armstrong",
    DriverId.CHRISTIAN_LUNDGAARD.value: "Christian Lundgaard",
    DriverId.YUKI_TSUNODA.value: "Yuki Tsunoda",
    DriverId.JEHAN_DARUVALA.value: "Jehan Daruvala",
    DriverId.GULHERME_SAMAIA.value: "Gulherme Samaia",
    DriverId.PEDRO_PIQUET.value: "Pedro Piquet",
    DriverId.FELIPE_DRUGOVICH.value: "Felipe Drugovich",
    DriverId.ROBERT_SCHWARTZMAN.value: "Robert Schwartzman",
    DriverId.ROY_NISSANY.value: "Roy Nissany",
    DriverId.MARINO_SATO.value: "Marino Sato",
    DriverId.AIDAN_JACKSON.value: "Aidan Jackson",
    DriverId.CASPER_AKKERMAN.value: "Casper Akkerman",
    DriverId.JENSON_BUTTON.value: "Jenson Button",
    DriverId.DAVID_COULTHARD.value: "David Coulthard",
    DriverId.NICO_ROSBERG.value: "Nico Rosberg",
    DriverId.OSCAR_PIASTRI.value: "Oscar Piastri",
    DriverId.LIAM_LAWSON.value: "Liam Lawson",
    DriverId.JURI_VIPS.value: "Juri Vips",
    DriverId.THEO_POURCHAIRE.value: "Theo Pourchaire",
    DriverId.RICHARD_VERSCHOOR.value: "Richard Verschoor",
    DriverId.LIRIM_ZENDELI.value: "Lirim Zendeli",
    DriverId.DAVID_BECKMANN.value: "David Beckmann",
    DriverId.ALESSIO_DELEDDA.value: "Alessio Deledda",
    DriverId.BENT_VISCAAL.value: "Bent Viscaal",
    DriverId.ENZO_FITTIPALDI.value: "Enzo Fittipaldi",
    DriverId.MARK_WEBBER.value: "Mark Webber",
    DriverId.JACQUES_VILLENEUVE.value: "Jacques Villeneuve",
    DriverId.JAKE_HUGHES.value: "Jake Hughes",
    DriverId.FREDERICK_VESTI.value: "Frederick Vesti",
    DriverId.OLLI_CALDWELL.value: "Olli Caldwell",
    DriverId.LOGAN_SARGEANT.value: "Logan Sargeant",
    DriverId.CEM_BOLUKBASI.value: "Cem Bolukbasi",
    DriverId.AYUMA_IWASA.value: "Ayuma Iwasa",
    DriverId.CLEMENT_NOVALAK.value: "Clement Novalak",
    DriverId.DENNIS_HAUGER.value: "Dennis Hauger",
    DriverId.CALAN_WILLIAMS.value: "Calan Williams",
    DriverId.JACK_DOOHAN.value: "Jack Doohan",
    DriverId.AMAURY_CORDEEL.value: "Amaury Cordeel",
    DriverId.MIKA_HAKKINEN.value: "Mika Hakkinen",
    DriverId.IGNASI_FIBLA.value: "Ignasi Fibla",
}
